# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
ad1 = np.array([1,2,3,4,5])
print("1 Dimensional array : ", ad1)
# Create a 2-dimensional NumPy array using np.array()
ad2 = np.array([[10,20,30,40,50],[15,25,35,45,55],[1,2,3,4,5]])
print("2 Dimensional array : ")
print(ad2)

1 Dimensional array :  [1 2 3 4 5]
2 Dimensional array : 
[[10 20 30 40 50]
 [15 25 35 45 55]
 [ 1  2  3  4  5]]


In [3]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
ad1.shape, ad1.ndim, ad1.dtype, ad1.size, type(ad1)


((5,), 1, dtype('int32'), 5, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
ad2.shape, ad2.ndim, ad2.dtype, ad2.size, type(ad2)

((3, 5), 2, dtype('int32'), 15, numpy.ndarray)

In [5]:
# Create an array of shape (5, 5) with only ones
aones=np.ones((5,5))
aones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Create an array of shape (3, 3, 5) with only zeros
azeros=np.zeros((3,3,5))
azeros

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [8]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arandom=np.random.randint(10,size=(7,2))
arandom

array([[2, 3],
       [8, 6],
       [4, 8],
       [6, 3],
       [0, 2],
       [0, 9],
       [0, 2]])

In [9]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arandom2=np.random.random((3,5))
arandom2

array([[0.80715777, 0.70794682, 0.30500111, 0.40877261, 0.81804581],
       [0.00388811, 0.30965343, 0.24105467, 0.70643357, 0.62504038],
       [0.25587195, 0.9325115 , 0.19839572, 0.86236251, 0.94378078]])

In [10]:
# Create an array of normally distributed random numbers
arand=np.random.normal(10,5,50)
arand

array([ 8.43773945, -2.02320491,  6.94165552, 13.64448242,  4.45102009,
        9.02043898, 10.84787071,  6.84657221,  7.01408707,  7.46950623,
       16.56399929,  7.28709753, 13.98905471, 12.74044033, 18.91975882,
       13.90309895, 12.76339873, 13.92839589, 12.60951088, 10.64461062,
        5.02371236,  3.73255015,  6.73476878,  9.2470187 , 15.80488029,
       13.54289879,  0.73169654, 15.18437211,  5.08050875, 11.69758995,
        7.40038606,  4.49619382,  6.62819599,  8.745441  , 10.11698698,
        8.97807908, 12.55418826, 15.93785378, 15.79500021, 11.2170401 ,
       17.92419877,  7.63290407,  5.87781673,  7.9942357 , 11.02263174,
       13.42387533,  8.14821853, 10.44835623, 12.41415505, 19.13012859])

In [11]:
# Set the random seed to 42
nseed=np.random.seed(42)
nseed
# Create a random array of numbers between 0 & 10 of size (4, 6)
aran=np.random.randint(10,size=(4,6))
aran

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [12]:
# Copy the code from the cell above and run it again
nseed=np.random.seed(42)
nseed
aran=np.random.randint(10,size=(4,6))
aran

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [13]:
# Find the 0'th index of the latest array you created
aran[0]

array([6, 3, 7, 4, 6, 9])

In [14]:
# Get the first 2 rows of latest array you created
aran[0:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

In [15]:
# Get the first 2 values of the first 2 rows of the latest array
aran[0:2,0:2]

array([[6, 3],
       [2, 6]])

In [16]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
arran=np.random.randint(10,size=(3,5))
arones=np.ones((3,5))
arran,arones

(array([[8, 0, 9, 2, 6],
        [3, 8, 2, 4, 2],
        [6, 4, 8, 6, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [17]:
# Add the two arrays together
a1=arran+arones
a1

array([[ 9.,  1., 10.,  3.,  7.],
       [ 4.,  9.,  3.,  5.,  3.],
       [ 7.,  5.,  9.,  7.,  2.]])

In [18]:
# Create another array of ones of shape (5, 3)
arone1=np.ones((5,3))
arone1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
a1+arone1

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [20]:
# Do the same operation you just did but this time with a transpose on one array
a2=a1+arone1.T
a2

array([[10.,  2., 11.,  4.,  8.],
       [ 5., 10.,  4.,  6.,  4.],
       [ 8.,  6., 10.,  8.,  3.]])

In [21]:
# Take the latest array to the power of 2 using the python way
a2**2

array([[100.,   4., 121.,  16.,  64.],
       [ 25., 100.,  16.,  36.,  16.],
       [ 64.,  36., 100.,  64.,   9.]])

In [22]:
# Do the same thing with numpy way
np.power(a2,2)

array([[100.,   4., 121.,  16.,  64.],
       [ 25., 100.,  16.,  36.,  16.],
       [ 64.,  36., 100.,  64.,   9.]])

In [23]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
np.mean(a2), np.min(a2), np.max(a2), np.std(a2), np.var(a2)

(6.6, 2.0, 11.0, 2.8000000000000003, 7.840000000000002)

In [24]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
a3=np.random.randint(10,size=(3,3))
a4=np.random.randint(10,size=(3,2))
a3,a4

(array([[3, 8, 1],
        [9, 8, 9],
        [4, 1, 3]]),
 array([[6, 7],
        [2, 0],
        [3, 1]]))

In [25]:
# Perform a dot product on the two newest arrays you created
np.dot(a3,a4)

array([[37, 22],
       [97, 72],
       [35, 31]])

In [26]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
b1=np.random.randint(10,size=(4,3))
b2=np.random.randint(10,size=(4,3))
b1,b2

(array([[7, 3, 1],
        [5, 5, 9],
        [3, 5, 1],
        [9, 1, 9]]),
 array([[3, 7, 6],
        [8, 7, 4],
        [1, 4, 7],
        [9, 8, 8]]))

In [27]:
# Perform a hadamard product on the two newest arrays you created
b1*b2

array([[21, 21,  6],
       [40, 35, 36],
       [ 3, 20,  7],
       [81,  8, 72]])

In [28]:
# Perform a dot product on the two newest arrays you created # Error anticipated
np.dot(b1,b2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [29]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
np.dot(b1.T,b2)

array([[145, 168, 155],
       [ 63,  84,  81],
       [157, 146, 121]])

In [30]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
c1=np.random.randint(10,size=(3,4))
c2=np.random.randint(10,size=(3,4))
c1,c2

(array([[0, 8, 6, 8],
        [7, 0, 7, 7],
        [2, 0, 7, 2]]),
 array([[2, 0, 4, 9],
        [6, 9, 8, 6],
        [8, 7, 1, 0]]))

In [31]:
# Compare the two arrays with '>', '<=' and '==' 
c1>c2

array([[False,  True,  True, False],
       [ True, False, False,  True],
       [False, False,  True,  True]])

In [32]:
c1<=c2

array([[ True, False, False,  True],
       [False,  True,  True, False],
       [ True,  True, False, False]])

In [33]:
c1==c2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [34]:
# Sort one of the arrays you just created in ascending order
np.sort(c2)

array([[0, 2, 4, 9],
       [6, 6, 8, 9],
       [0, 1, 7, 8]])

In [35]:
# Sort the indexes of one of the arrays you just created
np.argsort(c1)

array([[0, 2, 1, 3],
       [1, 0, 2, 3],
       [1, 0, 3, 2]], dtype=int64)

In [36]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(c1)

1

In [37]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [38]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(c1,axis = 1)

array([1, 0, 2], dtype=int64)

In [39]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(c1,axis = 0)

array([0, 1, 0, 2], dtype=int64)